title: Fica Theme
author: Involts
name: Involts
description: A modern theme with minimal look.
google_analytics: true
baseurl: "/jekyll-theme-fica/"
show_descriptions: true # set to true to show descriptions
# Links in Header
header:
  header_name_1: Download
  header_link_1: https://github.com/Involts/jekyll-theme-fica/archive/refs/tags/Fica-Theme-v1.0.zip
  header_name_2: Post
  header_link_2: /Post/
  header_name_3: About
  header_link_3: /About/
fica:
  date_format: "%b %-d, %Y"
      
plugins:
 - jekyll-feed
 - jekyll-seo-tag
exclude:
 - readme.md
